#' @export
#' @importFrom rgl rgl.postscript
#' @importFrom rgl rgl.light
#' @importFrom rgl rgl.viewpoint
#' @importFrom rgl clear3d
#' @param items The number of items to generate.
#' @param wd This is the working directory to save the figures in. If not provided, the file will be saved in the current working directory.
#' @param seed To generate the same set of item(s) on the local computer.
#' @param degree This allows you to change the rotation of the display figure by increasing or decreasing the value.
#' @description This function generates a 2 dimensional figure with 4 distractors and 1 answer.
#' @details By default the actual answer is always at half of the display polar coordinates. The display figure polar coordinates by default is 360. Increasing the degrees will make the figure rotate clock-wise and decreasing the degrees will make the figure rotate anti-clockwise.
#'
#'  4 distractors are generated. 2 of the generated distractors are a mirror image of the displayed figure. The difference in the polar coordinates between the two distractors are fixed at 120. The third distractor is a figure wihout the first square that is generated by the display item. The fourth distractor is a figure with an additional square added to the distractor. Currently, the polar coordinates are fixed for the third and fourth distractor as well.
#'
#' @author Aiden Loe
#' @title 2D Reasoning Items
#' @seealso \code{\link{lisy}}, \code{\link{arith}}
#' @return
#' \describe{
#' \item{ans}{Return the matrix that generates the display figure and answer.}
#' \item{mirror}{Return the matrix that generates a mirror figure.}
#' \item{dist3}{Return the matrix that generates the distractor without the first square.}
#' \item{dist4}{Return the matrix that generates the distractor that adds an extra square.}
#'     }
#' @examples
#' wd<- "~/desktop"
#' twoD(items=1, wd=wd,seed=NULL, degree=180)

 wd<- "~/desktop"
 twoD(items=1, wd=wd, seed=1, degree=180)

twoD <- function(items ,wd=NULL, seed=NULL, degree= 360){

  ##### From Here (HTML) ####
  if(is.null(wd)){
    wd = getwd()
    message("Item and distractors saved in current working directory.")
  }

#  wd<- "~/desktop"
#  items <- 2
#  degree<- 180
result <- NULL
for(item in 1:items){
# This will finalise the item
clear3d()
rgl.light()
clear3d(type = "lights") # for 2d
j <- NULL
k <- NULL
set.seed(seed)
vlist <- c(1,2,2)
(zlist <- matrix(NA,ncol=3,nrow=15))
for (i in 1:15) { # 15 is the max. Arbitary number. Can be anything. #Does not take last row
  cube(vlist[1],vlist[2],vlist[3])
  (step <- sample(1:3, 1))
  (vlist[step] <- vlist[step]+(-1)^rbinom(1,1,.25))
  (zlist[i,] <- vlist)
  zlist
}

clear3d()
cube(zlist[1:15,1],zlist[1:15,2],zlist[1:15,3])
rgl.viewpoint(theta = degree, phi = 90, fov = 0) # become 2D display item
save <- paste0(wd,"/display_",item,".pdf")
rgl.postscript(save,"pdf")

#Answer
rgl.viewpoint(theta = degree/2, phi = 90, fov = 0)
save <- paste0(wd,"/ans_",item,".pdf")
rgl.postscript(save,"pdf")


#Distractor 1
#mirror image
set.seed(seed)
clear3d()
mlist <- cbind(zlist[1:15,3],zlist[1:15,2],zlist[1:15,1])
cube(zlist[1:15,3],zlist[1:15,2],zlist[1:15,1]) #
rgl.viewpoint(theta = 380, phi = 90, fov = 0)
save <- paste0(wd,"/dist(mirror)_",item,".pdf")
rgl.postscript(save,"pdf")

#Distractor 2
#mirror image
set.seed(seed)
clear3d()
cube(zlist[1:15,3],zlist[1:15,2],zlist[1:15,1]) #
rgl.viewpoint(theta = 260, phi = 90, fov = 0)
save <- paste0(wd,"/dist(mirror2)_",item,".pdf")
rgl.postscript(save,"pdf")


#Distractor 3
# -1
(dlist2 <- zlist)
dlist3 <- dlist2[!duplicated(dlist2[,c(1,3)]),c(1:3)]
clear3d()
cube(dlist3[2:nrow(dlist3),1],dlist3[2:nrow(dlist3),2],dlist3[2:nrow(dlist3),3])

save <- paste0(wd,"/dist(3)_",item,".pdf")
rgl.postscript(save,"pdf")
#Distractor 4
# Adding an extra cube
set.seed(seed)
(dlist4 <- zlist)
if((dlist4[14,3] == dlist4[15,3])==TRUE){
dlist4[15,3]<-  dlist4[15,3]+1 # + 1 on the last column

}else if((dlist4[14,3] == dlist4[15,3]-2)==TRUE){
  dlist4[15,1]<-  dlist4[15,1]+1 #+ 1 at the start
  dlist4[15,3]<-  dlist4[15,3]+1 #+ 1 at the end

}else{
dlist4[15,1]<-  dlist4[15,1]+1 #+ 1 at the start
}
dlist4
zlist
clear3d()
cube(dlist4[1:15,1],dlist4[1:15,2],dlist4[1:15,3])

save <- paste0(wd,"/dist(4)_",item,".pdf")
rgl.postscript(save,"pdf")

name <- paste0('item_',item)

result[[name]] <- list(ans=zlist, mirror=mlist, dist3 = dlist3, dist4 = dlist4)


}

  result
  return(result)
  class(result) <- "twoD"

}

#first column, higher values, means on top of the square with the lower value
#second column, make the picture looks smaller as the number increase.
#3rd column, adding a cube forward or backward
